# Generated by Django 4.2 on 2026-02-13 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('editeur', models.CharField(max_length=200)),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('genre', models.CharField(choices=[('Romans', 'Romans'), ('Sciences', 'Sciences'), ('Histoire', 'Histoire'), ('BD', 'BD'), ('Jeunesse', 'Jeunesse'), ('Autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('disponible', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('emplacement', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Livres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retard', 'En retard'), ('retourne', 'Retourné'), ('perdu', 'Perdu')], default='en_cours', max_length=20)),
                ('nombre_jours_retard', models.IntegerField(default=0)),
                ('amende', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='gestion.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='gestion.membre')),
            ],
            options={
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
    ]
